### PR TITLE
Use cmake

### PR DESCRIPTION
**Pull request by mpre**
Using make and submodules to compile malva is a pain.   This MR adds support to cmake and uses system libraries instead of submodules.

Merges to development branch, not master.

### CODE REVIEW

**Review by yp — APPROVED** [review]
Looks good to me.

**Comment by yp** [comment]
`kmc` on Bioconda installs the include files to the root include directory instead of using a subdirectory `kmc/`. I added a commit to find `kmc_file.h` using cmake and to include that directory. Thus, compilation _should_ work on Bioconda, too.

**Comment by yp** [comment]
@mpre Could you give a look?

**Comment by mpre** [comment]
> @mpre Could you give a look?

Looks good to me too. Not really a fan of adapting the compile script to conda’s behavior but I see why it’s useful.

**Comment by yp** [comment]
I see your point. On the other, as you know, installing dependencies using conda (instead of system-wide) could be useful on shared systems.

**Pull request merged**
